name: video_player_example
description: Demonstrates how to use the video_player plugin.
publish_to: none
version: 1.1.0

environment:
  sdk: ^3.1.0
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fijkplayer_ijkfix: ^0.0.11

  # 状态管理
  # get: ^4.6.6
  get_it: ^7.6.7
  mobx: ^2.3.3+1
  flutter_mobx: ^2.2.1+1

  # 工具
  xml: ^6.5.0
  collection: ^1.18.0
  json_annotation: ^4.8.1
#  package_info_plus: ^6.0.0
  retry: ^3.1.2
  pretty_qr_code: ^3.3.0
    # 网络
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  http: ^1.2.1
  html: ^0.15.0
  # 日志
  talker: ^4.1.3
  talker_flutter: ^4.1.3
  # 数据存储
  shared_preferences: ^2.2.2
  # 界面适配
  flutter_screenutil: ^5.9.0
  # 国际化
  intl: ^0.18.1

dev_dependencies:
  build_runner: ^2.1.10
  path_provider: ^2.1.2
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/web/
