org.gradle.jvmargs=-Xmx4G
android.useAndroidX=true
android.enableJetifier=true
FLUTTER_BUILD_OBFUSCATE=true
FLUTTER_BUILD_SPLIT_DEBUG_INFO=debug_info
org.gradle.configureondemand=false
android.enableBuildCache=false
org.gradle.daemon=true
org.gradle.parallel=true
#org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx2048m
org.gradle.download.timeout=60000  # ???60?